// Generated by CoffeeScript 1.10.0
(function() {
  window.Main = (function() {
    function Main() {
      this._map = void 0;
      this._map_lot_layer = void 0;
      this._map_station_layer = void 0;
      this._map_search_area_layer = void 0;
      $(document).ready((function(_this) {
        return function() {
          return $.ajax({
            'url': 'config.json',
            'dataType': 'json',
            'success': function(config) {
              window.Config = config;
              _this.styleUI();
              _this._map = new Map("map");
              _this.resetMap();
              _this.loadXML("XSLT_Stations.xsl", "parkplatz/web/app.php/dbstation", "station");
              $('#station').change(function() {
                var option;
                option = $(this).children('option:selected');
                if ($(option).text() === 'Bitte auswählen') {
                  return _this.resetMap();
                } else {
                  return _this.update(option);
                }
              });
              return $(document).on('markerClicked', function(e) {
                return e.modal.find('.station-btn').click(function() {
                  e.modal.modal('hide');
                  return _this.update(this);
                });
              });
            }
          });
        };
      })(this));
    }

    Main.prototype.styleUI = function() {
      $('[data-toggle="select"]').select2();
      $('[data-toggle="checkbox"]').radiocheck();
      $('[data-toggle="radio"]').radiocheck();
      return $('[data-toggle="switch"]').bootstrapSwitch();
    };

    Main.prototype.resetMap = function() {
      return $.ajax({
        'url': 'deutschland.wkt',
        'dataType': 'text',
        'success': (function(_this) {
          return function(wkt) {
            var poi_url;
            _this.setSearchAreaLayer(wkt);
            poi_url = 'parkplatz/web/app.php/dbstation';
            _this.loadLotLayer(poi_url);
            _this.loadStationLayer(poi_url);
            return _this._map.zoomToExtent(_this._search_area_layer);
          };
        })(this)
      });
    };

    Main.prototype.loadLotLayer = function(url) {
      if (this._map_lot_layer != null) {
        this._map.removeLayer(this._map_lot_layer);
      }
      return this._map_lot_layer = this._map.addPois('Parkplätze', url, 2, 'img/parkinggarage.png', '#003399', 1, new CustomXMLLotFormat());
    };

    Main.prototype.loadStationLayer = function(url) {
      if (this._map_station_layer != null) {
        this._map.removeLayer(this._map_station_layer);
      }
      return this._station_lot_layer = this._map.addPois('Bahnhöfe', url, 1, 'img/dbstation.png', '#C20C0C', 1, new CustomXMLDBStationFormat());
    };

    Main.prototype.setSearchAreaLayer = function(wkt) {
      if (this._search_area_layer != null) {
        this._map.removeLayer(this._search_area_layer);
      }
      return this._search_area_layer = this._map.addShapes('Suchbereich', [wkt]);
    };

    Main.prototype.loadXML = function(xslurl, xmlurl, container_id) {
      return $.ajax({
        "url": xmlurl,
        "dataType": "xml",
        "success": (function(_this) {
          return function(xml) {
            return $.ajax({
              "url": xslurl,
              "dataType": "xml",
              "success": function(xsl) {
                return _this.xsltTransform(xml, xsl, container_id);
              }
            });
          };
        })(this)
      });
    };

    Main.prototype.xsltTransform = function(xml, xsl, container_id) {
      var content, result_d, xslt_p;
      $("#" + container_id).empty();
      if (window.ActiveXObject || ("ActiveXObject" in window)) {
        return content = xml.TransformNode(xsl);
      } else if (document.implementation && document.implementation.createDocument) {
        xslt_p = new XSLTProcessor();
        xslt_p.importStylesheet(xsl);
        result_d = xslt_p.transformToFragment(xml, document);
        return $("#" + container_id).append(result_d);
      } else {
        return alert('Browser wird nicht unterstützt');
      }
    };

    Main.prototype.update = function(element) {
      var lat, lon, radius, url, wkt;
      lon = parseFloat($(element).attr('data-longitude'));
      lat = parseFloat($(element).attr('data-latitude'));
      radius = parseInt($('#radius').val());
      if (lon && lat && radius) {
        url = "parkplatz/web/app.php/dbrange?radius=" + radius + "&long=" + lon + "&lat=" + lat;
        wkt = "CIRCLE (" + lon + " " + lat + " " + radius + ")";
        this.loadLotLayer(url);
        this.setSearchAreaLayer(wkt);
        this._map.zoomToExtent(this._search_area_layer);
        return this.loadXML("XSLT_Lots.xsl", url, "table");
      }
    };

    return Main;

  })();

  new Main();

}).call(this);
